### ISSUE TITLE
Add LangChain middleware to enable Python EEL code to connect with local LLM

### ISSUE THREAD

**Issue by kekoexchange** [kekoexchange/personal-llm#9]
# Summary

We need to connect the python script here with an LLM in order to provide chatbot functionality. This issue is to figure out how to write a single Python function that passes a message to the LLM and returns a response.

LangChain has something called [LangServe](https://github.com/users/kekoexchange/projects/1/views/3?pane=issue&itemId=56792435) that hosts a local REST API for endpoints such as this. We also could use the other parts of this library to call the LLM using Python code directly

# Acceptance Criteria

1. Write a function that can send a message to the LLM and get a response. The response for now does not have to be streaming.

**Comment by kayashaolu** [comment]
So actually discovered [ollama](https://ollama.com/) that can serve as a LLM backend. Check it out!

I think we can use this to download and run models and create a number of applications using ollama as an API for our LLM. So I'm converting this issue to use ollama to get a introductory chatgpt thing going locally!
